# name: Backend Lambda Deploy

# on:
#   push:
#     paths:
#       - "backend/lambda-function/**"   # Trigger ONLY when backend lambda changes
#     branches:
#       - master

# jobs:
#   deploy-backend:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}


#       # Zip Lambda code (Node/Python/etc)
#       - name: Zip Lambda Package
#         run: |
#           cd backend/lambda-function
#           zip -r lambda.zip ./*

#       # Update Lambda function code
#       - name: Deploy Lambda
#         run: |
#           aws lambda update-function-code \
#             --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} \
#             --zip-file fileb://backend/lambda-function/lambda.zip
